// <auto-generated />
using System;
using Lumos.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumos.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lumos.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Lumos.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lumos.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Lumos.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Giyim",
                            Description = "%100 Organik pamuktan üretilmiş rahat kesim hoodie.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
                            Name = "Premium Kapüşonlu Sweatshirt",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Giyim",
                            Description = "Zamansız tasarım, vintage yıkamalı kot ceket.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=1000&auto=format&fit=crop",
                            Name = "Klasik Denim Ceket",
                            Price = 2200m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Giyim",
                            Description = "Hem ofis hem günlük kullanıma uygun bej chino pantolon.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1000&auto=format&fit=crop",
                            Name = "Slim Fit Chino Pantolon",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Spor",
                            Description = "Yüksek performanslı koşucular için tasarlandı.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
                            Name = "Pro Koşu Ayakkabısı 2025",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ayakkabı",
                            Description = "İtalyan derisi, el yapımı klasik ayakkabı.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=1000&auto=format&fit=crop",
                            Name = "Deri Oxford Ayakkabı",
                            Price = 3400m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Aksesuar",
                            Description = "200 metreye kadar suya dayanıklı profesyonel dalgıç saati.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=1000&auto=format&fit=crop",
                            Name = "Profesyonel Dalgıç Saati",
                            Price = 5500m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Çanta",
                            Description = "Laptop bölmeli, su geçirmez kumaş sırt çantası.",
                            Gender = "erkek",
                            Image = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop",
                            Name = "Teknoloji Sırt Çantası",
                            Price = 1600m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Giyim",
                            Description = "Yaz davetleri için zarif ipek elbise.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop",
                            Name = "İpek Çiçekli Elbise",
                            Price = 3200m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Giyim",
                            Description = "Modern kesim, vatkalı şık ceket.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop",
                            Name = "Oversize Blazer Ceket",
                            Price = 2800m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Giyim",
                            Description = "90'lar modasını yansıtan yüksek bel jean.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop",
                            Name = "Yüksek Bel Jean",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Ayakkabı",
                            Description = "Özel davetler için tasarlanmış zarif topuklu.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop",
                            Name = "Zarif Topuklu Ayakkabı",
                            Price = 2750m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Çanta",
                            Description = "Geniş iç hacimli, %100 deri omuz çantası.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop",
                            Name = "Deri Omuz Çantası",
                            Price = 3100m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Spor",
                            Description = "Esnek kumaş, nefes alan yoga takımı.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=1000&auto=format&fit=crop",
                            Name = "Yoga ve Spor Takımı",
                            Price = 1900m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Aksesuar",
                            Description = "Altın kaplama, çoklu zincir kolye.",
                            Gender = "kadin",
                            Image = "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?q=80&w=1000&auto=format&fit=crop",
                            Name = "Altın Kaplama Kolye",
                            Price = 950m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Aksesuar",
                            Description = "Zamanın ötesinde bir tasarım. Safir cam.",
                            Gender = "unisex",
                            Image = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop",
                            Name = "Minimalist Kol Saati",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Aksesuar",
                            Description = "UV400 korumalı, klasik çerçeve güneş gözlüğü.",
                            Gender = "unisex",
                            Image = "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop",
                            Name = "Retro Güneş Gözlüğü",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Giyim",
                            Description = "Her dolapta olması gereken temel beyaz tişört.",
                            Gender = "unisex",
                            Image = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop",
                            Name = "Basic Beyaz Tişört",
                            Price = 450m
                        });
                });

            modelBuilder.Entity("Lumos.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@lumos.com",
                            Name = "Lumos Admin",
                            PasswordHash = "$2a$11$wo8srJ97/.UXMjL4Jo4xuurUKUeFd6SL/G0geIzPnrnUkFzv5XC5S",
                            Phone = "+90 555 000 00 00",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("Lumos.API.Models.Address", b =>
                {
                    b.HasOne("Lumos.API.Models.User", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumos.API.Models.Order", b =>
                {
                    b.HasOne("Lumos.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumos.API.Models.OrderItem", b =>
                {
                    b.HasOne("Lumos.API.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Lumos.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lumos.API.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
